spring:
  cloud:
    gateway:
      routes:
        - id: arrival-api
          uri: lb://ARRIVAL-API
          predicates:
            - Path=/arrival/**
          filters:
            - AuthenticationFilter

        - id: expense-service
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expenses/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging.level.org.springframework.web: DEBUG

server:
  port: 8080