server:
  port: 8080

logging.level.org.springframework.web: DEBUG

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: arrival-api
          uri: lb://ARRIVAL-API
          predicates:
            - Path=/arrival/**

        - id: expense-service
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expenses/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE-CLIENT-ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
          cognito:
            clientAuthenticationMethod: client_secret_post
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - phone
              - openid
              - email
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: http://localhost:8080/callback
        provider:
          google:
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
          cognito:
            issuerUri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_SO2QlXsQe
            user-name-attribute: username

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  region: eu-west-1
  cognito:
    user-pool-id: eu-west-1_SO2QlXsQe